---
title: "CV"
date: "17/07/2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Section A - Personal Details
Your Name: João \hfill Middle name: Rebouças 



Last name: Castello Branco					\hfill Date of birth: 12/20/1995

Address: 564, General Venâncio Flores St, apt 302, 
Leblon, Rio de Janeiro, Brazil.

Cellphone: +55 21 993017828 					\hfill Nationality: Brazilian  

Email: joaoreboucascastellobranco@gmail.com

### Section B - Previous Education
Bachelor's Degree in Economics at Federal University of Rio de Janeiro (UFRJ), Rio de Janeiro, Brazil  \hfill 08/2014 - 12/2018 

### Section B - Futher Information
 
#### Undergraduation thesis:

  *  The impact of ideology in education in Brazil using an 
    Regression Discontinuity Design (RDD) 
 
#### Work Experience:
 
  *   IDADOS Consulting: intensive use of Stata Software for data manipulation,
    data visualization and economic analysis. Creation of a forecast model
    for Brazil's unemployment rate with R (Feb./2018 - Mar / 2019)

  *   Monitor for the course Industrial Economics (two semesters, 2018) 

  *   Monitor for the course Political Economy I (one semester, 2016)

  *   Eletrobras - Finance Department
 
### Section C - Languages
Undergraduate education Language: Portuguese
Language Proficiency:

   * Portuguese: native
   * English: Fluent
       + TOEFL iBT Score: 103 
   * French: Intermediate
   * Spanish: Intermediate


 
